# Introduction

Some people consider using spreadsheets the table stakes for getting into data journalism. It's relatively easy to see what you're doing and you can easily share your work with your colleagues. In fact, pieces of the [Pulitzer-Prize winning COVID-19 coverage](https://www.pulitzer.org/winners/new-york-times-6) from The New York Times was compiled using an elaborate and highly tuned set of Google spreadsheets with dozens of contributors.

This guide uses Google Sheets, although you should be able to do these exercises with Excel on the Mac or Windows. Excel on the Mac is pretty good, bu Excel in Windows is very different -- it has much more capability for working with large and more complex data, and provides better tuning for import and other operations. There is a table that compares keystrokes for Apple desktops, laptops and Windows machines for Excel at the bottom of [An Excel Refresher](xl-refresher)

## Tutorials

Spreadsheets in the form of Google Sheets or Excel are used in almost every workplace in America. This section covers most of what you need in the newsroom, which is a different set of skills than in other businesses.

-   [An Excel Refresher](xl-refresher.html) : Start over with good habits

-   [Sorting and filtering to find stories](xl-filter-sort.html) : The first step of interviewing data

-   [Grouping with pivot tables](xl-pivot.html): Aggregating, and the super power of spreadsheets

-   [Formulas in Excel](xl-formulas.html): Percents, sums, and other basic computations used in newsrooms.

## Practice exercises

-   [Practice with "notice of claims" from Phoenix](xl-practice-noc.html): Filtering and pivot table practice using claims made against the city of Phoenix 2010-2020.
